version: 0.2

phases:
  install:
    commands:
      - echo install
  pre_build:
    commands:
      - export GIT_BRANCH=`git symbolic-ref HEAD --short 2>/dev/null`; if [ "$GIT_BRANCH" == "" ] ; then GIT_BRANCH=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'` && export GIT_BRANCH=${GIT_BRANCH#remotes/origin/} ; fi
      - export BRANCH=$GIT_BRANCH

      # 環境情報の表示
      - echo BRANCH $BRANCH

      # test
      - go test ./...
  build:
    commands:
      - go build